apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- was.yaml
- was-secret.yaml
- was-nlb.yaml


images:
- name: 621973965804.dkr.ecr.ap-northeast-2.amazonaws.com/wave-repo
  newTag: new_value
