apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was-server
  template:
    metadata:
      labels:
        app: was-server
    spec:
      containers:
      - name: was-server
        image: 621973965804.dkr.ecr.ap-northeast-2.amazonaws.com/wave-repo:4
        envFrom:
        - secretRef:
            name: db-info
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
