apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- web-cluster-ip.yaml
- web-ingress.yaml
- web.yaml
- web-secret.yaml


images:
- name: 950421566900.dkr.ecr.ap-northeast-2.amazonaws.com/wave-repo
  newTag: "88"
- name: 950421566900.dkr.ecr.ap-northeast-2.amazonaws.com/wave-repo-web
  newTag: "88"
