apiVersion: v1
data:
  WAS: azhzLWRlZmF1bHQtd2FzbmxiLTA2NjhkZTdiMDctZmY3YzVlZjE1ZGMwYWQwMy5lbGIuYXAtbm9ydGhlYXN0LTIuYW1hem9uYXdzLmNvbTo0MDAw
kind: Secret
metadata:
  name: was-port
---
apiVersion: v1
kind: Service
metadata:
  name: web-cluster
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: was-port
        image: 621973965804.dkr.ecr.ap-northeast-2.amazonaws.com/wave-repo-web:7
        name: web-server
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  name: web-ingress
spec:
  ingressClassName: alb-ingress-class
  rules:
  - http:
      paths:
      - backend:
          service:
            name: web-cluster
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb-ingress-class
spec:
  controller: ingress.k8s.aws/alb
