apiVersion: v1
data:
  DATABASE: b2xpdmVfeW91bmc=
  HOST: dGVzdC1kYi5janl1aWNxcTA2NzUuYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb20=
  PASSWD: cXdlcjEyMzQ=
  Port: MzMwNg==
  USER: YWRtaW4=
kind: Secret
metadata:
  name: db-info
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: internal
  name: was-nlb
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: was-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was-server
  template:
    metadata:
      labels:
        app: was-server
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-info
        image: 621973965804.dkr.ecr.ap-northeast-2.amazonaws.com/wave-repo:11
        name: was-server
        ports:
        - containerPort: 4000
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
